# 이곳이 github actions 플랫폼이며 곧 runnuer라고도 함 

name: CI
# dev로 push 되었을 때 실행해~! Trigger! 
on:
  push:
    branches: [dev]
# 해야할 작업들!
jobs:
  build:
    runs-on: ubuntu-latest
# 내가 만든 스프링부트 앱은 반드시 데이터베이스랑 연결을 해야 실행되므로  
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
# 내가 만든 스프링부트 환경변수가 셋팅 되어있으므로 환경 변수 셋팅!
    env:
      DB_HOST: localhost
      DB_NAME: testdb
      DB_USERNAME: testuser
      DB_PASSWORD: testpassword
# name 이 작업의 이름 actions/checkout@v2은  GitHub 리포지토리에서 소스 코드를 가져오는 역할
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# Java 개발 환경을 설정을 내가 만든 스프링부트 환경과 동일하게 만들기!
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Print environment variables
        run: |
          echo "DB_HOST=${DB_HOST}"
          echo "DB_NAME=${DB_NAME}"
          echo "DB_USERNAME=${DB_USERNAME}"
          echo "DB_PASSWORD=${DB_PASSWORD}"
# 빌드 실행 명령어!
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
        shell: bash
